name: Code Quality @owox/backend

on:
  pull_request:
    paths:
      - 'apps/backend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    timeout-minutes: ${{ matrix.check.timeout }}

    strategy:
      # If one check fails, the others will continue to run
      fail-fast: false
      matrix:
        check:
          - name: 'ESLint'
            command: 'npm run lint -w @owox/backend -- --max-warnings 0'
            timeout: 5
          - name: 'Prettier'
            command: 'npm run format:check -w @owox/backend'
            timeout: 5
          - name: 'Markdownlint'
            command: 'npm run lint:md -w @owox/backend'
            timeout: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.command }}
