name: Web Code Quality

on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      # If one check fails, the others will continue to run
      fail-fast: false
      matrix:
        check:
          - name: 'ESLint'
            command: 'npm run lint --workspace=@owox/web -- --max-warnings 0'
            timeout: 3
          - name: 'Prettier'
            command: 'npm run format:check --workspace=@owox/web'
            timeout: 3
          - name: 'TypeScript'
            command: 'npm run type-check --workspace=@owox/web'
            timeout: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.command }}
