name: Release PR
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changesets to work properly

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - run: npm ci --prefer-offline --no-audit --ignore-scripts --no-fund --loglevel error

      - uses: changesets/action@v1 # only creates/updates PR

      - name: Fix changelogs headings
        run: node tools/fix-changelog-headings.mjs

      - name: Commit fixed changelogs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore: fix changelog headings" || echo "No changes to commit"
          git push
