name: Test, Build and Audit @owox/connector-runner

on:
  pull_request:
    paths:
      - 'packages/connector-runner/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Test job
  test:
    name: ${{ matrix.test.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.test.timeout }}

    strategy:
      # If one check fails, the others will continue to run
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        test:
          - name: 'Overall test'
            command: 'npm run test -w @owox/connector-runner'
            timeout: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --ignore-scripts --no-fund --loglevel error

      - name: Run ${{ matrix.test.name }}
        run: ${{ matrix.test.command }}
        env:
          NODE_ENV: test

  # Audit job (by condition)
  audit:
    name: Audit @owox/connector-runner
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Check for changed paths'
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            workspace_changed:
              - 'packages/connector-runner/**'
            lockfile_changed:
              - 'package-lock.json'

      - name: Setup Node.js
        if: steps.filter.outputs.workspace_changed == 'true' && steps.filter.outputs.lockfile_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Run Audit @owox/connector-runner
        if: steps.filter.outputs.workspace_changed == 'true' && steps.filter.outputs.lockfile_changed == 'true'
        run: npm audit -w @owox/connector-runner
