name: Test, Build and Audit @owox/ui

on:
  pull_request:
    paths:
      - 'packages/ui/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Audit job (by condition)
  audit:
    name: Audit @owox/ui
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Check for changed paths'
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            workspace_changed:
              - 'packages/ui/**'
            lockfile_changed:
              - 'package-lock.json'

      - name: Setup Node.js
        if: steps.filter.outputs.workspace_changed == 'true' && steps.filter.outputs.lockfile_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Run Audit @owox/ui
        if: steps.filter.outputs.workspace_changed == 'true' && steps.filter.outputs.lockfile_changed == 'true'
        run: npm audit -w @owox/ui
